somsolet_backoffice_dashboard:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{env_var('DB_HOST')}}"
      port: "{{env_var('DB_PORT') | as_number }}"
      dbname: "{{env_var('DB_NAME')}}"
      user: "{{env_var('DB_USER')}}"
      password: "{{env_var('DB_PASSWORD')}}"
      schema: public
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
